### ISSUE TITLE
Unconventional released zip-fil

### ISSUE THREAD

**Issue by hartenthaler** [Jefferson49/ChangeLanguageWithURL#3]
Normally you can download a released webtrees zip-file, unzip it and copy the content to modules_v4. In your case this does not work, you have to copy the subfolder "change_language_with_url". Maybe you can change this or at least describe it in the README.

**Comment by Jefferson49** [comment]
Thanx for the feedback. The extra folder in the ZIP file was automatically generated by GitHub while creating the release with an assigned tag. The tag was generated into the extra folder name. I also do not prefer/like this.

I will try to find out, how this can be avoided by a configuration in GitHub for the next release.

**Comment by Jefferson49** [comment]
Described the installation of the subfolder in the Readme.md file.
